In [1]:
import pandas as pd
data = [
    [60,65,66],
    [80,85,88],
    [100,100,100]
]
df = pd.DataFrame(data)
df

     0    1    2
0   60   65   66
1   80   85   88
2  100  100  100

表データの列項目のことを「ヘッダー」、行番号のことを「インデックス」と呼ぶ

In [20]:
import pandas as pd
# pandas は pdとして一般的にはimportするらしい
df = pd.DataFrame(
    {
        "Name": ["A男","B郎","C子"],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
    })
df

  Name  Age     Sex
0   A男   22    male
1   B郎   35    male
2   C子   58  female

In [21]:
df.head(2)

  Name  Age   Sex
0   A男   22  male
1   B郎   35  male

In [10]:
import pandas as pd
# pandas は pdとして一般的にはimportするらしい
df = pd.DataFrame(
    {
        "Name": ["A男","B郎","C子"],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
    })
df.head(2)

  Name  Age   Sex
0   A男   22  male
1   B郎   35  male

In [16]:
import pandas as pd
df = pd.DataFrame({
    "名前": ["田中", "佐藤", "鈴木", "山田"],
    "年齢": ["25", "30", "35", "40"],
    "年収": [350, 450, 550, 650],
    "部署": ["営業", "開発", "開発", "営業"]
})
df.index = range(1,len(df["年齢"])+1)
df

   名前  年齢   年収  部署
1  田中  25  350  営業
2  佐藤  30  450  開発
3  鈴木  35  550  開発
4  山田  40  650  営業

In [17]:
df.describe()

               年収
count    4.000000
mean   500.000000
std    129.099445
min    350.000000
25%    425.000000
50%    500.000000
75%    575.000000
max    650.000000

In [13]:
import pandas as pd
data = [
        ["ノートPC_A","PC","120000",2],
        ["マウス","周辺機器","3000",5],
        ["キーボード","周辺機器","8000",3],
        ["モニター","周辺機器","35000",2],
        ["ノートPC_B","PC","130000",1]
        ]
col = ["商品名","カテゴリ","単価","数量"]

#indexが１始まりになるように再設定
idx = range(1,len(data)+1) 
df = pd.DataFrame(data=data, columns=col, index=idx)
df

       商品名  カテゴリ      単価  数量
1  ノートPC_A    PC  120000   2
2      マウス  周辺機器    3000   5
3    キーボード  周辺機器    8000   3
4     モニター  周辺機器   35000   2
5  ノートPC_B    PC  130000   1

In [12]:
df = df.drop(columns=["カテゴリ"])
df

       商品名      単価  数量
1  ノートPC_A  120000   2
2      マウス    3000   5
3    キーボード    8000   3
4     モニター   35000   2
5  ノートPC_B  130000   1